/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InternalRouteImport } from './routes/internal'
import { Route as NekudaRouteImport } from './routes/nekuda'
import { Route as NitzanRouteImport } from './routes/nitzan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalRoute = InternalRouteImport.update({
  id: '/internal',
  path: '/internal',
  getParentRoute: () => rootRouteImport,
} as any)
const NekudaRoute = NekudaRouteImport.update({
  id: '/nekuda',
  path: '/nekuda',
  getParentRoute: () => rootRouteImport,
} as any)
const NitzanRoute = NitzanRouteImport.update({
  id: '/nitzan',
  path: '/nitzan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/internal': typeof InternalRoute
  '/nekuda': typeof NekudaRoute
  '/nitzan': typeof NitzanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/internal': typeof InternalRoute
  '/nekuda': typeof NekudaRoute
  '/nitzan': typeof NitzanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/internal': typeof InternalRoute
  '/nekuda': typeof NekudaRoute
  '/nitzan': typeof NitzanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/internal' | '/nekuda' | '/nitzan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/internal' | '/nekuda' | '/nitzan'
  id: '__root__' | '/' | '/internal' | '/nekuda' | '/nitzan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InternalRoute: typeof InternalRoute
  NekudaRoute: typeof NekudaRoute
  NitzanRoute: typeof NitzanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal': {
      id: '/internal'
      path: '/internal'
      fullPath: '/internal'
      preLoaderRoute: typeof InternalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nekuda': {
      id: '/nekuda'
      path: '/nekuda'
      fullPath: '/nekuda'
      preLoaderRoute: typeof NekudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nitzan': {
      id: '/nitzan'
      path: '/nitzan'
      fullPath: '/nitzan'
      preLoaderRoute: typeof NitzanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InternalRoute: InternalRoute,
  NekudaRoute: NekudaRoute,
  NitzanRoute: NitzanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
